// MOVIE
export const GET_MOVIE_LIST_START = 'GET_MOVIE_LIST_START'
export const GET_MOVIE_LIST_FAIL = 'GET_MOVIE_LIST_FAIL'
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS'

// SEARCH
export const GET_SEARCH_LIST_START = 'GET_SEARCH_LIST_START'
export const GET_SEARCH_LIST_FAIL = 'GET_SEARCH_LIST_FAIL'
export const GET_SEARCH_LIST_SUCCESS = 'GET_SEARCH_LIST_SUCCESS'
export const SET_SEARCH_TEXT = 'GET_SEARCH_TEXT'
export const SHOW_AUTOCOMPLETE = 'SHOW_AUTOCOMPLETE'

// SET DATE
export const SET_START_DATE = 'SET_START_DATE'
export const SET_FINISH_DATE = 'SET_FINISH_DATE'
export const GET_LIST_BY_DATE = 'GET_LIST_BY_DATE'
export const GET_LIST_BY_DATE_ERROR = 'GET_LIST_BY_DATE_ERROR'

// DETAILS
export const GET_MOVIE_DETAILS_START = 'GET_MOVIE_DETAILS_START'
export const GET_MOVIE_DETAILS_FAIL = 'GET_MOVIE_DETAILS_FAIL'
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS'