// EVENT
export const SEARCH_EVENTS_START = 'SEARCH_EVENTS_START';
export const SEARCH_EVENTS_FAIL = 'SEARCH_EVENTS_FAIL';
export const SEARCH_EVENTS_SUCCESS = 'SEARCH_EVENTS_SUCCESS';
export const SELECT_EVENT = 'SELECT_EVENT';

export const GET_NEAREST_EVENT_LIST_START = 'GET_NEAREST_EVENTS_LIST_START';
export const GET_NEAREST_EVENT_LIST_FAIL = 'GET_NEAREST_EVENTS_LIST_FAIL';
export const GET_NEAREST_EVENT_LIST_SUCCESS = 'GET_NEAREST_EVENTS_LIST_SUCCESS';

export const GET_EVENT_DETAILS_START = 'EVENT_DETAILS_START';
export const GET_EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL';
export const GET_EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS';

export const GET_EVENT_LIST_START = 'GET_EVENT_LIST_START';
export const GET_EVENT_LIST_FAIL = 'GET_EVENT_LIST_FAIL';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';

// CATEGORY
export const GET_CATEGORY_LIST_START = 'GET_CATEGORY_LIST_START';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';

// CITY
export const GET_CITY_LIST_START = 'GET_CITY_LIST_START';
export const GET_CITY_LIST_FAIL = 'GET_CITY_LIST_FAIL';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const SELECT_CITY = 'SELECT_CITY';

export const SEARCH_CITY_START = 'SEARCH_CITY_START';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';

export const FIND_NEAREST_CITY_START = 'FIND_NEAREST_CITY_START';
export const FIND_NEAREST_CITY_FAIL = 'FIND_NEAREST_CITY_FAIL';
export const FIND_NEAREST_CITY_SUCCESS = 'FIND_NEAREST_CITY_SUCCESS';
